//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace EmployeesManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Employees1 = new HashSet<Employee>();
            this.Teams = new HashSet<Team>();
            this.Teams1 = new HashSet<Team>();
        }
    
        public int EmployeeID { get; set; }
        
        //[Required(ErrorMessage = "{0} is required!")]
        //[Display(Name = "First Name")]
        public string FirstName { get; set; }

        //[Required(ErrorMessage = "{0} is required!")]
        //[Display(Name = "Last Name")]
        public string LastName { get; set; }

        public int JobPositionID { get; set; }

        //[Required(ErrorMessage = "{0} is required!")]
        //[Display(Name = "Salary")]
        public decimal Salary { get; set; }

        public int TownID { get; set; }

        //[Required(ErrorMessage = "{0} is required!")]
        //[DataType(DataType.EmailAddress)]
        //[Display(Name = "Email")]
        //[RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*",
        //    ErrorMessage = "Invalid email")]
        //[Remote("CheckIfEmailExist", "Employee", ErrorMessage = "Another employee use this email. Please enter another email!")]
        public string Email { get; set; }

        //[Required(ErrorMessage = "{0} is required!")]
        //[Display(Name = "Phone")]
        public string Phone { get; set; }

        public Nullable<int> ManagerID { get; set; }
    
        public virtual ICollection<Employee> Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual JobPosition JobPosition { get; set; }
        public virtual Workplace Workplace { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<Team> Teams1 { get; set; }
    }
}
