//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace EmployeesManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int TeamID { get; set; }

        //[Required(ErrorMessage = "{0} is required!")]
        //[Display(Name = "Team name")]
        public string Name { get; set; }
        public int ManagerID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }


    }
}
